version: '3.8'
services:
  java_app:
    build:
      context: ./onlineShop
    ports: 
      - "8089:8089"
    depends_on:
      - postgres
      - mongo

  postgres:
    container_name: postgres_server_container3
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: online_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  mongo:
    container_name: mongo_container3
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: online_shop
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  pgadmin:
    container_name: pgadmin4_container3
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - postgres

volumes:
  db-data:
  pgadmin-data:
  mongo-data: